# Generated by Django 5.1.3 on 2025-03-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full-stack', 'Full-stack'), ('Mobile', 'Mobile'), ('Data Science', 'Data Science'), ('Other', 'Other')], default='Frontend', max_length=20)),
            ],
        ),
    ]
