# Generated by Django 5.1.3 on 2025-04-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_developerprofile_delete_programmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='expertise',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Fullstack', 'Fullstack'), ('Data science', 'Datas cience'), ('Machine learning', 'Machine learning'), ('Cyber security', 'Cyber security')], default='Frontend', max_length=100),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='git_repo',
            field=models.URLField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='user',
            field=models.CharField(max_length=555),
        ),
    ]
