# Generated by Django 5.1.3 on 2025-04-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='quiz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
