# Generated by Django 5.1.3 on 2025-02-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0003_customuser_profile_picture_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
