# Generated by Django 5.1.3 on 2025-04-11 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0008_alter_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outcome', models.CharField(max_length=50)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount_won', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='regis.account')),
            ],
        ),
    ]
