# Generated by Django 5.1.3 on 2025-05-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0009_spinhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpinHistory',
        ),
    ]
